add chunks
htmlacademy-ecmascript/238048-cinemaddict-14 pull request #3
Opened 2021-04-15 12:07 UTC by IrinaSer

2021-04-15 19:34 UTC, obzhorash requested changes

2021-04-15 19:34 UTC, obzhorash commented on src/main.js
> +const commentedFilmsContainerElement = filmsElement.querySelectorAll('.films-list--extra')[filmsElement.querySelectorAll('.films-list--extra').length - 1];
ТАк конечно лучше не делать filmsElement.querySelectorAll('.films-list--extra') два раза обращаться к dom лучше сохранить в переменную и с ней работать

2021-04-15 21:58 UTC, obzhorash requested changes
Не весь рефакторинг откатываем. функции создания шаблона должны только создавать шаблон, им не нужно знать количество фильмов. 
+ названия не очень хорошие all-films лучше films-list
films-template.js просто films

2021-04-16 11:04 UTC, IrinaSer commented on src/main.js
> +const commentedFilmsContainerElement = filmsElement.querySelectorAll('.films-list--extra')[filmsElement.querySelectorAll('.films-list--extra').length - 1];
Рефакторинг откатила, вынесла querySelectorAll в переменную

2021-04-16 11:05 UTC, merged